name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/my-web-api:latest, ${{ secrets.DOCKERHUB_USERNAME }}/my-web-api:${{ github.run_number }} 
  update_server:
      name: Updating prod environment
      runs-on: ubuntu-latest
      needs: docker
      steps:
        - name: Replacing container
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.SERVER_HOSTNAME }}
            username: ${{ secrets.SERVER_USERNAME }}
            password: ${{ secrets.SERVER_PASSWORD }}
            script: |
              docker image pull saifdev22/my-web-api:latest
              docker container stop test-web
              docker container prune -f
              docker run -d --name test-web --restart unless-stopped -p 32770:8080 saifdev22/my-web-api:latest
              docker image prune -f
